#!/bin/bash

# Verifica se um comando foi passado
if [ "$#" -lt 1 ]; then
    echo "Uso: caco [build|clean|test]"
    exit 1
fi

# Executa o comando make com o alvo apropriado
case $1 in
    build)
        make build
        ;;
    clean)
        make clean
        ;;
    test)
        make test
        ;;
    *)
        echo "Comando desconhecido: $1"
        echo "Uso: caco [build|clean|test]"
        exit 1
        ;;
esac
